Add default repository labels
cisagov/.github pull request #29
Opened 2021-12-04 17:02 UTC by hillaryj

#  #

## 🗣 Description ##

Adds a file to use as configuration for GitHub label standardization using https://github.com/cisagov/github-label-management

## 💭 Motivation and context ##

New repositories inherit labels from the `.github` repository, so using the tool and updating this `.github` repository will keep this repository and both new and old repos updated.

## 🧪 Testing ##

This was the file I used last year when standardizing repository labels, before I left 😭 . This will wrap up the work.

## ✅ Checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - _eschew scope creep!_
- [ ] _All_ future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

2021-12-04 17:03 UTC, hillaryj commented
Unfortunately, I can no longer add type-of-change labels, but this is otherwise all checked off.

2021-12-06 17:12 UTC, jsf9k approved these changes

2021-12-06 17:13 UTC, jsf9k commented
The prodigal teammate returns!

2021-12-06 18:32 UTC, dav3r requested changes
I noticed a few tiny things that I'd like to see changed, but great to hear from you @hillaryj 😄

2021-12-06 18:32 UTC, dav3r commented on repo-labels.json
> +    "description": "This issue will not be worked on ",
Remove an unintended space:
```suggestion
    "description": "This issue will not be worked on",
```

2021-12-06 18:32 UTC, dav3r commented on repo-labels.json
> +    "description": "Good for newcomers",
Update wording to align more closely with other descriptions:
```suggestion
    "description": "This issue is a good candidate for newcomers to work on",
```

2021-12-06 18:32 UTC, dav3r commented on repo-labels.json
> +    "description": "This pull request is ready to merge during the next Lineage kraken release",
Make capitalization in description match that in the name field and add single quotes:
```suggestion
    "description": "This pull request is ready to merge during the next Lineage 'Kraken' release",
```

2023-02-10 20:57 UTC, dav3r commented
I'm closing this PR, as it's functionality has been superceded by https://github.com/cisagov/skeleton-generic/pull/118.

2023-02-10 20:57 UTC, closed without merging